app:
    resource: '@RecipeBundle/Controller/'
    type: annotation
admin:
    resource: '@RecipeBundle/Controller/Admin/'
    type: annotation

login:
    path:     /login
    defaults: { _controller: "RecipeBundle:Security:login" }

logout:
    path:     /logout
