version: '2'
services:
  app:
    container_name: recipes_app
    hostname: recipes_app
    build:
      context: ./
      dockerfile: ./provisioning/app/Dockerfile
    restart: always
    environment:
      - TERM=xterm
      - SYMFONY_ENV=dev
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=r00t
      - MAILER_HOST=mailhog
      - MAILER_USER=null
      - MAILER_PASSWORD=null
    links:
      - db
      - mailhog
    volumes:
      - ./:/var/www/html

  http:
    container_name: recipes_http
    hostname: recipes_http
    build:
      context: ./
      dockerfile: ./provisioning/http/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    volumes:
      - ./:/var/www/html

  db:
    container_name: recipes_db
    hostname: db
    image: "mariadb:latest"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql

  mailhog:
    container_name: recipes_mailhog
    hostname: mailhog
    image: "mailhog/mailhog"
    restart: always
    ports:
      - 8025:8025

  phpmyadmin:
    container_name: recipes_phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=r00t
    links:
      - db
    restart: always
    ports:
     - 8080:80
