version: '2'
services:
  web:
    build: web
    container_name: recipes_web
    hostname: recipes
    restart: always
    environment:
      - TERM=xterm
      - ENV=dev
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=192.168.0.50
      - PHP_IDE_CONFIG=serverName=dev.recipes.co.uk
      - SSH_AUTH_SOCK=/tmp/agent.sock
    links:
      - db
      - mailhog
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /codebase/recipes/:/app
      - /data/recipes/:/data
      - ${SSH_AUTH_SOCK}:/tmp/agent.sock
      - ~/.ssh:/app/.ssh
      - ~/.gitconfig:/app/.gitconfig
  db:
    image: "mariadb:latest"
    container_name: recipes_db
    hostname: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
    ports:
      - "3306:3306"
    volumes:
      - /data/recipes/mysql/:/var/lib/mysql

  mailhog:
    container_name: recipes_mailhog
    hostname: mailhog
    image: "mailhog/mailhog"
    restart: always
    ports:
      - 8025:8025

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=r00t
    links:
      - db
    restart: always
    ports:
     - 9999:80
