parameters:
    database_host: "%env(DATABASE_HOST)%"
    database_port: 3306
    database_name: recipes
    database_user: "%env(DATABASE_USER)%"
    database_password: "%env(DATABASE_PASSWORD)%"
    mailer_transport: smtp
    mailer_host: "%env(MAILER_HOST)%"
    mailer_user: "%env(MAILER_USER)%"
    mailer_password: "%env(MAILER_PASSWORD)%"
    secret: jhvhdsjkthj4k65h45jk6th45jghdfuty3h24534t
